### ISSUE TITLE
Pyinstaller on this repo misses "Interfaces" and "Forwarders"

### ISSUE THREAD

**Issue by mbhatt1** [ssh-mitm/ssh-mitm#101]
**Describe the bug**
Running pyinstaller on this repo misses "interfaces" like mirrorshell and "forwarders". 

**To Reproduce**
pyinstaller --onefile --clean sshmitm/cli.py
./dist/cli server --help 

**Expected behavior**
Doing python3 ./sshmitm/cli.py server --help shows forwarders and interfaces. I'd expect that. 

**Screenshots**
<img width="769" alt="image" src="https://user-images.githubusercontent.com/5893997/166440545-34783085-3b94-4773-b04b-4870f5140e9f.png">

**Desktop (please complete the following information):**
 - Should be irrelevant but it's FreeBSD 12

**Comment by mbhatt1** [comment]
Might be doing something dumb. :) Just thought to check here

**Comment by manfred-kaiser** [comment]
Pyinstaller has problems with entrypoints, but entrypoints are used to find the plugins.

There are some questions and answers on stackoverflow: https://stackoverflow.com/questions/48884766/pyinstaller-on-a-setuptools-package 
Perhaps those can help to get SSH-MITM running with pyinstaller.

If you have python installed on your machine and you only need to deploy SSH-MITM as a single file, you can use [SHIV](https://github.com/linkedin/shiv)

**Comment by manfred-kaiser** [comment]
**Running SSH-MITM with pyinstaller:**

Create the executable with pyinstaller:

```bash
mkdir packages
pip install --target ./packages/ ssh-mitm
pyinstaller --onefile --paths=packages -n ssh-mitm sshmitm/cli.py
```

The built executable is called "ssh-mitm" and can be found in the **dist** folder.
