### ISSUE TITLE
removeing @typechecked decorator will remove development complexity

### ISSUE THREAD

**Issue by zoey-fux** [ssh-mitm/ssh-mitm#109]
You have annotated all you classes and functions. While this helps to find bug easier, it add an additional layer of complexity.

Typechecks also reduces the performance of your application and you need to call it with `PYTHONOPTIMIZE=1`

I think it's better to do it the other way and only add typechecks during development.

`typeguard` has an importhook, which allows to annotate all functions and classes with the `@typechecked`-decorator.

You can add in `cli.py` following code before importing your sshmitm modules:

```python
if os.getenv('TYPECHECKED'):
    from typeguard import importhook
    importhook.install_import_hook('sshmitm')
```

With those changes, you only need to call your application with: `TYPECHECKED=1 ssh-mitm server`

**Comment by manfred-kaiser** [comment]
Your idea is interesting. I will remove all occurrences of `@typechecked` and add the importhook to `cli.py`
