### ISSUE TITLE
Forwarded SSH Agent not available on the remote server

### ISSUE THREAD

**Issue by manfred-kaiser** [ssh-mitm/ssh-mitm#129]
### SSH-MITM Version

3.0.2

### Platform detail

Linux

### Arguments used to start SSH-MITM

ssh-mitm server

### SSH client used

OpenSSH

### SSH server used

OpenSSH

### What steps will reproduce the bug?

Start SSH-MITM: 
`ssh-mitm server`

Connect to SSH-MITM and forward the agent:
`ssh -p 10022 -A localhost`

When connected to the remote server, start a new SSH session from the already running session:
`ssh -p 10022 -A localhost`

```
Remote authentication failed
         Remote Address: 127.0.0.1:22
         Username: testuser
         Remote-Publickey: ssh-rsa SHA256:aXXXXXXX 3072bits
         Agent: no agent

ERROR    ❗ ssh agent keys are not allowed for signing. Remote authentication not possible.
```

### What should have happened?

If the client forward the agent, the agent should also forwarded to the remote server.

For example, if the user wants to connect to another server like a git repository from the remote machine, this would.

**Comment by tuanchoang** [comment]
Hi @manfred-kaiser,

Are there any plans to fix this bug? It seems like I am running into this issue as I've seen "Authentication timeout" errors in my ssh-mitm logs which could be related to this.

My scenario is I'm running ssh-mitm on my localhost and mapping the remote server to a private Gitlab instance. For some repositories, it works fine. But every so often there's a repository where the authentication would fail.

**Comment by manfred-kaiser** [comment]
Forwarding the agent from ssh-mitm to the server is on my roadmap and I will try to implement it in one of the next major releases.

To your scenario. 

I don't think your problem is related to the missing agent forwarding to the server, because a git server does not use a forwarded agent for further authentication.

I have some documentation on how to intercept git: https://docs.ssh-mitm.at/user_guide/advanced-usage.html

Have you tried to set the ``GIT_SSH_COMMAND`` variable before executing some git commands?

**Comment by tuanchoang** [comment]
@manfred-kaiser Thanks for the insight! Here's the scenario/use case I am trying:

1. In a shell script, I would want to clone a git repository via SSH using the same exact URL as if there wasn't ssh-mitm enabled. For example: ```git clone git@github.com:ssh-mitm/ssh-mitm.git```
2. In this instance, if I were to enable ```ssh-mitm```, this is what I would start it with: ```ssh-mitm --debug --paramiko-log-level debug server --remote-host github.com --scp-interface debug_traffic --session-log-dir ~/ssh-mitm/logs --store-ssh-session```
3. In ~/.ssh/config (on the same host running ```ssh-mitm```), I would also have this:
```
Host github.com
    User git
    Hostname 127.0.0.1

Host 127.0.0.1
    User git
    ForwardAgent yes
    Port 10022
    StrictHostKeyChecking no

Host *
    IdentityFile ~/.ssh/id_rsa
    ServerAliveInterval 30
    ServerAliveCountMax 10
```

With this ```~/.ssh/config``` and ```ssh-mitm``` running, if I were to run ```git clone git@github.com:ssh-mitm/ssh-mitm.git```, the idea is that cause the host ```github.com``` has a hostname of 127.0.0.1, it would flow through ```ssh-mitm``` which is configured on port 10022 with ```github.com``` as the remote host and the user as ```git```.

As you can see, in the scenario, my SSH key would need to be configured in the actual github.com and thus, the SSH agent needs to be enabled and forwarded.

In theory and practice, this scenario does work occasionally. However, for certain large repositories (e.g. https://github.com/etcd-io/etcd), I would frequently run into situations where the authentication will time out while it's unpacking among other things.

Hope that clarifies things. :)

**Comment by Dulin0411** [comment]
Hi, @manfred-kaiser ,

Seems like I meet this problem:
![image](https://github.com/ssh-mitm/ssh-mitm/assets/141405559/af874483-fb2b-47cf-ad84-85064b0c652f)

I want to use your tool to decode ssh message. ssh client is running at win7--ssh-mitm is running at VM ubuntu--ssh server is running at another VM ubuntu

when I input 'ssh -p 10022 -A root@192.168.10.10(ssh-mitm ip)', I got this error.

I have tried to use win7 as ssh-mitm, same result.

So, I want to know how to avoid this bug?

**Comment by manfred-kaiser** [comment]
This error should be fixed or it was a mistake when testing the implemented feature.

It was tested with 2 users.

User1 was intercepted by SSH-MITM. This works as expected.

User1 is able to connect with user2 to an ssh server, because the agent is forwarded by SSH-MITM.

It's also possible to use the hijacked session to login to another server.
