### ISSUE TITLE
exception in  Transport._parse_newkeys()

### ISSUE THREAD

**Issue by mrjy81** [ssh-mitm/ssh-mitm#148]
### SSH-MITM Version

3.0.2

### Platform detail

kali,windows 10 

### Arguments used to start SSH-MITM

ssh-mitm server --remote-host localhost

### SSH client used

plink , openssh

### SSH server used

ssh mitm server

### What steps will reproduce the bug?

when i want to accept fingerprint it throw an error Transport._parse_newkeys() takes 2 arguments but 3 were given and connection and session will be closed in client side

### What should have happened?

![image](https://github.com/ssh-mitm/ssh-mitm/assets/86535407/dc8f795e-9dca-42db-a523-ee5fe1a7ec8b)

**Comment by manfred-kaiser** [comment]
The reason for this error are changes in the private api from paramiko.

There is an other issue #143 for updating paramiko to the latest version.

At the moment the paramiko version is pinned to an older release in pyproject.toml to avoid problems during development of SSH-MITM: https://github.com/ssh-mitm/ssh-mitm/blob/5c72948dc460e6a97778731b3880571b829a0e01/pyproject.toml#L38

Sadly, the published version on pypi.org has no version pin which will install the latest paramiko version which is incompatible to the current stable version of SSH-MITM.

I will try to release a new version in the next days.

**Comment by mrjy81** [comment]
thank you very much i have a question and  it's nice of you if you answer
it I'm beginner with this tool and whenever i try to connect it locally i
can't i tried with putty and in vbox kali but sometimes say Remote
Authentication failed or in windows putty i received no supported
authentication methods available server sent:publickey and tool say
winerror 10061 target machine actively refused it what's the problem is it
because ssh2 is secure and this tool works with ssh1

please help me thanks in advance

**Comment by manfred-kaiser** [comment]
Please open a new issued ticket for new questions, which or not related to your first question. I will create a new issue for this question #149
