### ISSUE TITLE
Various problems with windows ssh clients

### ISSUE THREAD

**Issue by manfred-kaiser** [ssh-mitm/ssh-mitm#149]
thank you very much i have a question and  it's nice of you if you answer
it I'm beginner with this tool and whenever i try to connect it locally i
can't i tried with putty and in vbox kali but sometimes say Remote
Authentication failed or in windows putty i received no supported
authentication methods available server sent:publickey and tool say
winerror 10061 target machine actively refused it what's the problem is it
because ssh2 is secure and this tool works with ssh1

please help me thanks in advance

**Comment by manfred-kaiser** [comment]
SSH-MITM supports SSH2. It does not support SSH1.

SSH2 is still secure. You can compare it with other tools like proxy servers for HTTPS. The existence of a tool to intercept the traffic does not mean a protocol like ssh is broken.

Such tools are intended for security audits and in such cases the user must bypass security features.

Without further information, it's hard to help you.

Can you provide a stack trace or debug logs from SSH-MITM?

It's also good if you xan provide verbose logs or error messages from your clients.

It's also necessary to know the concrete scenario.

One problem might be the implementation of public key authentication. At the moment it's recommended to have only a few keys in the agent. For testing purposes you should use 2 keys. More keys can result in authentication issued. See #127 

Perhaps you are using an old version of SSH-MITM, if you used some community packages.

**Comment by mrjy81** [comment]
thans i'm using ssh-mitm version 3.0.2 and windows 10 on the clinet side 
ssh -p 10022 test@localhost
The authenticity of host '[localhost]:10022 ([::1]:10022)' can't be established.
RSA key fingerprint is .....
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[localhost]:10022' (RSA) to the list of known hosts.
test@localhost: Permission denied (publickey).

and in the server side ssh-mitm 
 ℹ session 8e271b98-d2c8-42b3-a5d8-8758113863c3 created
[09/07/23 22:16:27] INFO     ℹ client information:
                               - client version: ssh-2.0-openssh_for_windows_8.1
                               - product name:
                               - vendor url:
                             ⚠ client audit tests:
                               * client uses same server_host_key_algorithms as OpenSSH
                               * client seems to connect for the first time or using a default key order
                               * Preferred server host key algorithm: ecdsa-sha2-nistp256-cert-v01@openssh.com
[09/07/23 22:16:34] ERROR    Unable to connect to localhost: [WinError 10061] No connection could be made because the
                             target machine actively refused it
[09/07/23 22:16:38] ERROR    Unable to connect to localhost: [WinError 10061] No connection could be made because the
                             target machine actively refused it
                    ERROR    Socket exception: An existing connection was forcibly closed by the remote host (10054)
                    WARNING  (('::1', 60588, 0, 0)->('::1', 10022, 0, 0)) session not started
                    INFO     ℹ session 8e271b98-d2c8-42b3-a5d8-8758113863c3 closed

**Comment by manfred-kaiser** [comment]
Are you running SSH-MITM on the windows machine? I created some windows executables, but they are not well tested. (I have no windows machine)

You should run SSH-MITM on a linux machine an I recommend you to use the AppImage.

```ERROR Unable to connect to localhost: [WinError 10061] No connection could be made because the
target machine actively refused it```

Perhaps some security tools are blocking the connection, because the connection was refused and anither was closed by the remote host.

But again, without more information about your scenario it's only guessing.

**Comment by mrjy81** [comment]
thank you so much my problem solved when i setup server in linux machine i really appreciate your assistance
