### ISSUE TITLE
mkdir doesn't work when proxying sftp

### ISSUE THREAD

**Issue by mlocutus** [ssh-mitm/ssh-mitm#151]
### SSH-MITM Version

SSH-MITM 3.0.2

### Platform detail

mac os (ARM), linux

### Arguments used to start SSH-MITM

ssh-mitm server --session-log-dir ssh-mitm --store-scp-files --remote-host localhost --store-sftp-files --listen-port 2638  --hide-credentials  --ssh-interface base

### What steps will reproduce the bug?

start ssh-mitm
try to scp a directory (from mac)
```
scp  -r  -P 2638 dir1 username@localhost:~/tmp/.
```

or use SecureFX to copy a directory from client to server

### What should have happened?

directory should have been created, instead a failure is returned.  the directory is not made

### Additional information

it appears that the client doesn't send `attr.st_mode` as part of the mkdir request.  the sshmitm interfaces/sftp.py checks to see if st_mode is set and if it is not returns an error. however, in this case i wonder if it's acceptable to just use the defaults instead of returning an error

**Comment by manfred-kaiser** [comment]
Thanks for the bug report. I will test it and accept your merge request if all tests will succeed during my tests.

**Comment by manfred-kaiser** [comment]
this issue should be fixed with pull #152
