### ISSUE TITLE
New `requirements.in` file is missing from v4.1.0 PyPI sdist

### ISSUE THREAD

**Issue by p-linnane** [ssh-mitm/ssh-mitm#159]
### SSH-MITM Version

4.1.0

### Platform detail

Source code

### Arguments used to start SSH-MITM

N/A

### What steps will reproduce the bug?

The new `requirements.in` file is missing from v4.1.0 PyPI sdist, which prevents building it successfully.

### What should have happened?

ssh-mitm v4.1.0 should build from the PyPI sdist.

**Comment by manfred-kaiser** [comment]
Thanks for the bug report. I have created a new release 4.1.1 to fix this issue 👍🏻

**Comment by p-linnane** [comment]
Confirming this is resolved. Thank you!
