### ISSUE TITLE
Packages for Linux Distributins

### ISSUE THREAD

**Issue by manfred-kaiser** [ssh-mitm/ssh-mitm#38]
It would be nice, if ssh-mitm is available through the distributions package management systems.

- Kali Linux
- BlackArch
- Ubuntu
- Debian
- ...

**Comment by gratuxri** [comment]
Kali, Ubuntu are Debian-based, you need to get it to Debian. Look at https://www.debian.org/devel/wnpp/ for RFP (Request for Packaging)
I have prepared packaging for debian: https://salsa.debian.org/gratuxri/python-ssh-mitm
Here is aur packaging for archlinux: https://aur.archlinux.org/packages/python-ssh-mitm/

**Comment by gratuxri** [comment]
https://code.launchpad.net/~gratuxri/+recipe/python-ssh-mitm-daily

**Comment by manfred-kaiser** [comment]
Thanks for creating the packages.

How does it work, when I release a new version of ssh-mitm on github or pypi?

**Comment by gratuxri** [comment]
At the moment it looks for pypi packages

**Comment by manfred-kaiser** [comment]
Thanks for the help. I will maintain AppImage, Flatpak and Snap.
