### ISSUE TITLE
Only one channel permitted at a time

### ISSUE THREAD

**Issue by Strider3000** [ssh-mitm/ssh-mitm#45]
**Describe the bug**
ssh-mitm complains about only one channel being able to be opened. It also complains about SFTP.

**To Reproduce**
Find a device that doesn't support SCP / SFTP / is a rudimentary SSH server.
Run ssh-mitm against it.

**Expected behavior**
I expected it to work fine.

**Screenshots**
See [screenshot]([url](url
![err](https://user-images.githubusercontent.com/3498412/111689032-843b0900-87f9-11eb-94f1-1f36d1b8ecff.jpg)
))

**Desktop (please complete the following information):**
 - OS: Win 10 x64

**Additional context**
The targeted SSH server is a bit on the rudimentary side.

**Comment by Strider3000** [comment]
I can get you an IP and port for the server I used if needed.

**Comment by manfred-kaiser** [comment]
At the moment, ssh-mitm opens 2 channels. One is for the initial session and the second is for sftp.
I will add an optional parameter to disable sftp channels.

**Comment by Strider3000** [comment]
Was this addressed in 0.5.0? If so I'll test

**Comment by manfred-kaiser** [comment]
sorry, this issue was not fixed in 0.5.0.
In 0.5.0 full support for port forwarding was added.

When I have some free time, I will fix this issue, so you can use ssh-mitm with only one channel.

**Comment by manfred-kaiser** [comment]
I have created a bug fix release 0.5.1.
Can you install the latest version an test it with your server?
Version 0.5.1 is available on Pypi: https://pypi.org/project/ssh-mitm/

I have tested it with OpenSSH, where I set the option "MaxSessions 1", which allows only one connection.

**Comment by Strider3000** [comment]
Hi @manfred-kaiser I have tested version 0.5.1 and it did work successfully with my ssh server. thanks!

**Comment by manfred-kaiser** [comment]
no problem ;-)
