### ISSUE TITLE
Add support for Dropbear client

### ISSUE THREAD

**Issue by frankl1m** [ssh-mitm/ssh-mitm#46]
Dropbear SSH server endpoint on iPhone SE 14.4 is working unstable when SSH-mitm is enabled basically all SFTP requests crash it, some example below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp_client.py", line 130, in __init__
    server_version = self._send_version()
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp.py", line 134, in _send_version
    t, data = self._read_packet()
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp.py", line 201, in _read_packet
    x = self._read_all(4)
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp.py", line 188, in _read_all
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ssh_proxy_server/clients/sftp.py", line 32, in from_client
    sftp._sftp = paramiko.SFTPClient.from_transport(ssh_client.transport)
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp_client.py", line 170, in from_transport
    return cls(chan)
  File "/usr/local/lib/python3.9/site-packages/paramiko/sftp_client.py", line 132, in __init__
    raise SSHException("EOF during negotiation")
paramiko.ssh_exception.SSHException: EOF during negotiation

**Comment by frankl1m** [comment]
If you can be compatible with libssh2 wrapper would be great

**Comment by manfred-kaiser** [comment]
Perhaps this problem is related with #45 

At the moment ssh-mitm opens 2 channels for convenience reasons. With this approach, ssh-mitm is able to transfer files from to the server without an initial sftp connection.

I will fix this problem in release 0.6.0 which will be released in may 2021.

**Comment by frankl1m** [comment]
This a litle and dont important but can be good for organization, on this command --scp-interface store_file for example using WInscp not advice and not store file transfered, thanks any way

**Comment by manfred-kaiser** [comment]
Paramiko has some problems with dropbear clients and servers. SSH-MITM has some workarounds to deal with dropbear.

I don't have a iPhone to test this scenario :-(

Which version of dropbear server are you using? Perhaps I can test it with this version of dropbear on my dev machine.

**Comment by manfred-kaiser** [comment]
> This a litle and dont important but can be good for organization, on this command --scp-interface store_file for example using WInscp not advice and not store file transfered, thanks any way

I have created a bug fix release for ssh-mitm. Can you test it with your WinSCP client please.

**Comment by frankl1m** [comment]
> Which version of dropbear server are you using? Perhaps I can test it with this version of dropbear on my dev machine.

default on Checkar1n jailbreak dont know exactly

**Comment by manfred-kaiser** [comment]
If you have terminal access (ssh) perhaps you can execute the command "dropbear -V". This should give you the installed version.

If you can not find the dropbear executable, you can ask the developer of jeckra1n, which version of dropbear is insalled with your jailbreak and I will implement a workarround for this dropbear version.

I can't support specific ssh servers from iOS jailbreaks, because I don't have test devices :-(

**Comment by frankl1m** [comment]
Dropbear v2019.78, i am testing with OpenSSH  for iOS, with dropbear now is not even listing files i send some logs for you verify in some mins

**Comment by frankl1m** [comment]
scp and ssh protocol not issue at this moment but scp is bring new erros

**Comment by frankl1m** [comment]
Check the logs for test i used sw.plist iOS openssh , dropbear is crashing not listing file i think that some words are being omitted
[dropbear@127.0.0.1.zip](https://github.com/ssh-mitm/ssh-mitm/files/6414398/dropbear%40127.0.0.1.zip)
[openssh@127.0.0.1.zip](https://github.com/ssh-mitm/ssh-mitm/files/6414401/openssh%40127.0.0.1.zip)

**Comment by frankl1m** [comment]
without SSH-MITM all work perfectly

**Comment by manfred-kaiser** [comment]
I will test ssh-mitm with dropbear server v2019.78 in the next days.

**Comment by frankl1m** [comment]
other ask multi channel is not implemented yet right?

**Comment by manfred-kaiser** [comment]
**Client --> ssh-mitm: possible**

the client can create a multiplexed channel to ssh-mitm. This channel can be used for multiple connections.

If you are using an openssh client, you can create the master channel with `ssh -M -S /controll/path remotehost`

This connection can be used with: `ssh -S /controll/path remotehost`

**ssh-mitm --> SSH Server: not possible - paramiko can not create multiplexed connections**

ssh-mitm does not support multiplexed connection to a remote host with a multiplexed channel. ssh-mitm creates a new channel for each connection. Even if the client uses a multoplexed channel.

ssh-mitm uses paramiko for handling the ssh protocol. There is an open issue for paramiko (https://github.com/paramiko/paramiko/issues/852) for implementing multiplexing sice 2017.

As long as paramiko does not support multiplexing, ssh-mitm is not able to create muliplexed connections to a server.
