### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by manfred-kaiser** [ssh-mitm/ssh-mitm#54]
The documentation of SSH-MITM should be improved.

Please help me to write a better documentation. What can you do:

- fix spelling errors and improve the english
- add vulnerabilities for ssh clients and server. At the moment, only openssh, putty and dropbear are documented
- improve or write tutorials how to use ssh-mitm (supported plugins, arp spoofing, ...)

**Comment by janbbeck** [comment]
Ok, so what I will do to get familiarity with this is to:

- Start with just checking spelling and grammar on all the text files.
- Then work on combining Installation and Quick Start. 
- Then see what can be done about Advanced Usage. 
- Then maybe CVE descriptions.

Does this seem like a good approach?

**Comment by manfred-kaiser** [comment]
Thanks for helping :smiley: 

In 'Advances Useage' I described, how to intercept public key authentication. This works for most use cases, but this was the wrong approach. So the public key authentication part has to be rewritten. I will do that in november 2021 (public disclosure)

Currently I'm working on the next major release of ssh-mitm, which will change some things. 

The next release will provide a simple GUI, which is intended for beginners and it looks good in screenshots :wink: 

One major change will affect the logging. Plugins in the current version 0.x.x used different arguments to store intecepted sessions and files. This will be combined in a single argument. If a plugin wants to store some files, this global setting will be used instead of different arguments. Note: Logging was never documented...

If you want to change the other parts, that's ok :+1:

**Comment by manfred-kaiser** [comment]
> The next release will provide a simple GUI, which is intended for beginners and it looks good in screenshots

Flatpaks are only listed on https://flathub.org if they provide a gui :disappointed: 
Perhaps I will readd support for flatpaks and this is a requirement to get listed.

**Comment by janbbeck** [comment]
Unreasonably excited for a GUI :P

**Comment by manfred-kaiser** [comment]
I have created a new issue, where we can discuss the gui: #65
