### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Darkcast** [ssh-mitm/ssh-mitm#63]
in a scenario were the attacker has access to the box is there a way that one could run this to hijack any new ssh conenction incoming to the port 22 would the attacker need sudo ?

Thank you

**Comment by manfred-kaiser** [comment]
_The port numbers below 1024 are considered privileged ports. Normal users and processes are not allowed to use them for various security reasons._

This means you need sudo or the root user.

**Capabilities and authbind**

If you want to run SSH-MITM without root privileges, you can also use [CAP_NET_BIND_SERVICE](http://man7.org/linux/man-pages/man7/capabilities.7.html) or [authbind](http://manpages.ubuntu.com/manpages/hardy/man1/authbind.1.html). Using capabilities or authbind does not work, if port 22 is already in use. 

To stop a current ssh daemon and to configure both tools, you need root privileges.

**Firewall/iptables**

If you are allowed to set firewall rules, than you can redirect port 22 to another port, which does not require to stop a running process, which is using port 22.

```iptables -A PREROUTING -t nat -p tcp --dport 22 -j REDIRECT --to-port 10022```
