### ISSUE TITLE
Unable to use ssh-mitm

### ISSUE THREAD

**Issue by ibuetler** [ssh-mitm/ssh-mitm#85]
**Describe the bug**

unable to use ssh-mitm

```
Traceback (most recent call last):
ssh-mitm_1        |   File "/usr/lib/python3.8/site-packages/enhancements/modules.py", line 495, in get_sub_modules
```

used in https://github.com/Hacking-Lab/alpine-ssh-mitm

Ivan

**Comment by manfred-kaiser** [comment]
Can you provide a full stacktrace please?

I think, you are using an old version of enhancements. 

Latest versions:

* enhancements 0.2.7
* ssh-mitm 0.6.1

Which version of ssh-mitm and enhancements are you using?

**Comment by manfred-kaiser** [comment]
Thanks for the bug report. The problem was, that the hostname regex was to strict. 

I have created a new release (0.6.3) where the error is fixed.
