### ISSUE TITLE
TypeError: check_global_request() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by yosida95** [ssh-mitm/ssh-mitm#87]
**Describe the bug**

`paramiko.server.ServerInterface` requires `check_global_request` to take 3 positional arguments, but `ssh_proxy_server.interfaces.ServerInterface.check_global_request` takes only 2 positional arguments.

https://github.com/paramiko/paramiko/blob/a598ca14d6451343c69be97e0e1c65eb15c0e607/paramiko/server.py#L345

https://github.com/ssh-mitm/ssh-mitm/blob/21b5d8439e787bc7334518f2284238122661991f/ssh_proxy_server/interfaces/server.py#L281

```
[11/18/21 15:39:36] ERROR    Unknown exception: check_global_request() takes 2 positional arguments but 3 were given
                    ERROR    Traceback (most recent call last):
                    ERROR      File "/snap/ssh-mitm/27/lib/python3.6/site-packages/ssh_proxy_server/workarounds/dropbear.py", line 123, in transport_run
                    ERROR        self._handler_table[ptype](self, m)
                    ERROR      File "/snap/ssh-mitm/27/lib/python3.6/site-packages/paramiko/transport.py", line 2644, in _parse_global_request
                    ERROR        ok = self.server_object.check_global_request(kind, m)
                    ERROR    TypeError: check_global_request() takes 2 positional arguments but 3 were given
```

**To Reproduce**

1. Launch ssh-mitm: `ssh-mitm --remote-host 127.0.0.1:22`
2. Connect to the ssh-mitm instance: `ssh -p 10022 user@example.com`
3. Wait for a while

**Expected behavior**

The TypeError exception does not happen and the connection keeps alive.

**Comment by manfred-kaiser** [comment]
Thanks for the bug report and the fix
