### ISSUE TITLE
Request for docs on specific use case: intercepting proxy traffic

### ISSUE THREAD

**Issue by unsocial-bleach** [ssh-mitm/ssh-mitm#94]
I have a specific use case, and I'm looking for help creating documentation for this use case.

I want to intercept all outgoing SSH connections from the computer I'm running ssh-mitm on. The computer is running a proxy for a lot of web traffic and SSH connections of users I need to pen test, and I want to intercept outgoing connections from the proxy.

How can I set up routing tables to perform this? I'm assuming I need to run ssh-mitm in transparent mode, but I'm having trouble following the rest of the guide.

Any help directly, or by means of creating formal documentation would be quite helpful. I can help create docs for others wishing to do this if someone can help get me started. Thank you!

**Comment by manfred-kaiser** [comment]
Currently the "transparent mode" is experimental and support for specific use cases is not always possible. 
This is a small project and I'm the only developer :disappointed: 

If you can provide more information, it's easier for me to support you with your use case.

Transparent mode is based on the kernel [TProxy](https://www.kernel.org/doc/html/v5.12/networking/tproxy.html) feature.

> I want to intercept all outgoing SSH connections from the computer I'm running ssh-mitm on. The computer is running a proxy for a lot of web traffic and SSH connections of users I need to pen test, and I want to intercept outgoing connections from the proxy.

You wrote, that your computer is running as a proxy. What do you mean with "outgoing ssh connections"? Is your computer used as a jump host or is it used as a gateway? 

Is it possible to provide a network diagram?

**Comment by unsocial-bleach** [comment]
Hello, [this](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=VPN-SSH-MITM#R5Vhdc5swEPw1fkzGQsaxHxPiNp1p0jTOtOlTR2MUUC10jBA27q%2BvBOLLxE7ScU2bPplbTiDt7Z5kBtiLsveSxOE1%2BJQPnKGfDfDlwHEQwo7%2BMcimQMauWwCBZL5NqoE5%2B0ktOLRoynyatBIVAFcsboMLEIIuVAsjUsK6nfYIvP3WmAS0A8wXhHfRr8xXYYFOnLMav6IsCO2b3QkubkSkzLULSULiw7oB4dkAexJAFVdR5lFuuCtpKca923G3mpekQr1kQLYUbL36%2FhlFMHtQ93fpzZKejO3c1KZcL%2FX18m0IUoUQgCB8VqMXElLhU%2FPUoY7qnI8AsQaRBn9QpTa2liRVoKFQRdzepRlTD43rb%2BZRp66NLjP75DzYlIFQcvPQDBqjTFgPy6NyXLE%2Bs6idtFkogVQu6B6urJAVkQFVe%2FJGVXG1KShEVM9Hj5OUE8VW7XkQq86gyqsrqC9sEV9RUDvJFeGpfdN8fqUBjzOzYGeIcm0umQhq0zAQua0MC0mYULmiEp0uIBrgc8fpSKQtgHXIFJ3HJOdurZtAu9h2PlQqmu0vQZcyO2BsHWQ7CJraeF37EZUuCxteLMcdnGS3Q3IfNjqgtPGRpJ0PPZeSbBoJMTChksaTbw1Ql9%2BZtOuPtxvdM%2FllXFe8mEFd%2F2opvy8J%2FJzvnBf6zvlrfef07rvyTPB2jDd6ofGmfRjPLY9qpQDc%2Fcbr5KMjGA91d7z%2FRBNoh3uPLIrp60SB8RFEMepo4lNMxZfbGw3O8zZreEqFKNqxbtUn1x%2FurzvCeabHtlVzgI6Lt7euUd8t96zDpFftXVolQyi4rOjdIlBTodqcJUrCknrAQWpEgDD2e2Scb0GEs0DocKGp06%2FAF4ZYpv%2BXndsbEfP93LtPFenglak2v7IyuFuZ8ROFwX%2BqMNNOYZ48urdVbopj5d%2Bz0sdo61A%2F6VvpCO1m1PkHGcXD3hntHorvaJByYjrGvXdrjsfNZvJWe4eLt3pHuSUevnfosP6iVOym9Wc5PPsF) is the diagram I am trying to describe. Thanks!

**Comment by unsocial-bleach** [comment]
I stumbled across a tool that supports a similar MITM tool (mitmproxy) that also has a Transparent Proxy mode. This guide here appears very helpful and transferable for what I was trying to achieve. I have yet to try it with ssh-mitm, but will throw it here for the time being. https://docs.mitmproxy.org/stable/howto-transparent/

**Comment by neo2020000** [comment]
Hello 
I have this error when run this command :
ssh-mitm server --remote-host 192.168.100.200
error :          ERROR    Exception (server): Client kex "e" is out of range                                                                                                                                                              
                    ERROR    Traceback (most recent call last):                                                                                                                                                                              
                    ERROR      File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2137, in run                                                                                                                                
                    ERROR        self.kex_engine.parse_next(ptype, m)                                                                                                                                                                        
                    ERROR      File "/usr/lib/python3/dist-packages/paramiko/kex_group1.py", line 73, in parse_next                                                                                                                          
                    ERROR        return self._parse_kexdh_init(m)                                                                                                                                                                            
                    ERROR      File "/usr/lib/python3/dist-packages/paramiko/kex_group1.py", line 127, in _parse_kexdh_init                                                                                                                  
                    ERROR        raise SSHException('Client kex "e" is out of range')                                                                                                                                                        
                    ERROR    paramiko.ssh_exception.SSHException: Client kex "e" is out of range

**Comment by neo2020000** [comment]
and this command is not working :
ssh-mitm  server--client-tunnel inject --tunnel-client-dest google.com:80 --server-tunnel inject

**Comment by manfred-kaiser** [comment]
Can you provide more information please.

It seems you are using an old version of SSH-MITM.

Please answer following questions:

* Which version of SSH-MITM are you using?
* Wich version of paramiko is used?
* Which remite server are you using and which version?

**Comment by neo2020000** [comment]
Thanks for your responding.

SSH-MITM 2.0.5
paramiko 2.10.4 
i don't understand this question:  "Which remote server are you using and which version?"

**Comment by manfred-kaiser** [comment]
SSH-MITM is based on paramiko. Since paramiko is not compatible to all clients and servers, it's important tonknow ehich versions are used.

Perhaps your problem is related tonthe latest changes in paramiko, which are necessary to be compatible with OpenSSH 8.9  and later.

Wich client should be intercepted and which server is used as the remote server?

See #95 and #84

**Comment by manfred-kaiser** [comment]
> 
> And i have this error  ==> This command is in your documnet 
> command : ssh-mitm  server --client-tunnel inject --tunnel-client-dest google.com:80 --server-tunnel inject                                                                                                                                    
> 
> Error:
> 
> usage: ssh-mitm [-h] [-V] [-d] [--paramiko-log-level {warning,info,debug}] [--disable-workarounds] subcommand ...
> ssh-mitm: error: unrecognized arguments: --client-tunnel inject --tunnel-client-dest google.com:80 --server-tunnel inject
> 

Can you provide a link or filename where xou have found the command, so this can be fixed.

**Comment by neo2020000** [comment]
This is where i find it:
https://docs.ssh-mitm.at/portforwarding.html

Thank you for this app

**Comment by manfred-kaiser** [comment]
can you provide mor information which client and server were used during your tests. This would help me to reproduce the error.

Currently I'm testing SSH-MITM with current OpenSSH versions.

**Comment by manfred-kaiser** [comment]
I have updated the documentation and added a chapter about transparent proxy mode: https://docs.ssh-mitm.at/user_guide/transparent.html
